### ISSUE TITLE
Gestione livelli di accesso (ruoli)

### ISSUE THREAD

**Issue by giutrec** [AssociazionePrometeo/gianomanager#2]
pagina in cui si deve poter inserire/modificare/eliminare i livelli utente e definire cosa possono fare

**Comment by mattbit** [comment]
- [x] support for user groups
- [x] seed default groups (admin & default)
- [x] admin area to manage groups
- [x] assign roles to users
- [x]  configure groups permissions
- [x] add authorization gate

**Comment by mattbit** [comment]
Most of the work is done! see commit fb9a26896b3c3a7426fda13c34f51a05c11b0740

What’s missing:
- [x] move permission strings in a proper class
- [x] improve validation in `RoleController`
- [x] fix tests: now a generic user cannot manage the resources
- [x] add specific rules for user management  
This is required otherwise a normal user with the `user-create` permission could create an administrator and escalate privileges! Only admin users must be able to assign the admin group.
- [x] hide buttons and navigation elements based on user permissions
